[package]
name = "reward-system"
version = "0.1.0"
description = "Reward system for NFT distribution based on interactions"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "reward_system"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.0"
anchor-spl = "0.30.0"
mpl-core = { version = "0.1.0", features = ["no-entrypoint"] }

