-- GENERATED by prisma/build-bootstrap.mjs - do not edit by hand.
-- Idempotent: creates missing tables/columns/indexes/foreign keys, drops nothing.
-- Apply with: node prisma/apply-bootstrap.mjs

BEGIN;

-- users
CREATE TABLE IF NOT EXISTS "users" (
    "id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- wallets
CREATE TABLE IF NOT EXISTS "wallets" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "wallet_address" TEXT NOT NULL,
    "wallet_type" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "wallets_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "wallets" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "wallets" ADD COLUMN IF NOT EXISTS "user_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "wallets" ADD COLUMN IF NOT EXISTS "wallet_address" TEXT NOT NULL DEFAULT '';
ALTER TABLE "wallets" ADD COLUMN IF NOT EXISTS "wallet_type" TEXT NOT NULL DEFAULT '';
ALTER TABLE "wallets" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "wallets" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- nfts
CREATE TABLE IF NOT EXISTS "nfts" (
    "id" TEXT NOT NULL,
    "wallet_id" TEXT NOT NULL,
    "nft_id" TEXT NOT NULL,
    "event_id" TEXT,
    "badge_id" TEXT,
    "mint_timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata_uri" TEXT NOT NULL,
    "name" TEXT NOT NULL,

    CONSTRAINT "nfts_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "wallet_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "nft_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "event_id" TEXT;
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "badge_id" TEXT;
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "mint_timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "metadata_uri" TEXT NOT NULL DEFAULT '';
ALTER TABLE "nfts" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '';

-- escrows
CREATE TABLE IF NOT EXISTS "escrows" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "nft_id" TEXT NOT NULL,
    "amount" DECIMAL(65,30) NOT NULL,
    "status" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "escrows_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "escrows" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "escrows" ADD COLUMN IF NOT EXISTS "user_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "escrows" ADD COLUMN IF NOT EXISTS "nft_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "escrows" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(65,30) NOT NULL DEFAULT 0;
ALTER TABLE "escrows" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT '';
ALTER TABLE "escrows" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "escrows" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- transactions
CREATE TABLE IF NOT EXISTS "transactions" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "amount" DECIMAL(65,30) NOT NULL,
    "nft_id" TEXT,
    "transaction_type" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "transaction_id" TEXT NOT NULL,
    "wallet_address" TEXT,
    "tx_hash" TEXT,
    "currency" TEXT,
    "network" TEXT,
    "metadata" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "transactions_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "user_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(65,30) NOT NULL DEFAULT 0;
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "nft_id" TEXT;
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "transaction_type" TEXT NOT NULL DEFAULT '';
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT '';
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "transaction_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "wallet_address" TEXT;
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "tx_hash" TEXT;
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "currency" TEXT;
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "network" TEXT;
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "metadata" TEXT;
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- payment_logs
CREATE TABLE IF NOT EXISTS "payment_logs" (
    "id" TEXT NOT NULL,
    "event_type" TEXT NOT NULL,
    "charge_id" TEXT NOT NULL,
    "charge_code" TEXT,
    "wallet_address" TEXT,
    "tx_hash" TEXT,
    "amount" DECIMAL(65,30),
    "currency" TEXT,
    "network" TEXT,
    "status" TEXT NOT NULL,
    "raw_payload" TEXT,
    "verified" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payment_logs_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "event_type" TEXT NOT NULL DEFAULT '';
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "charge_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "charge_code" TEXT;
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "wallet_address" TEXT;
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "tx_hash" TEXT;
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(65,30);
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "currency" TEXT;
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "network" TEXT;
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT '';
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "raw_payload" TEXT;
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "verified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "payment_logs" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- events
CREATE TABLE IF NOT EXISTS "events" (
    "id" TEXT NOT NULL,
    "creator_id" TEXT NOT NULL,
    "creator_wallet" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "entry_fee" DECIMAL(65,30) NOT NULL,
    "event_date" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "completed_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "events_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "creator_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "creator_wallet" TEXT NOT NULL DEFAULT '';
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "entry_fee" DECIMAL(65,30) NOT NULL DEFAULT 0;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "event_date" TIMESTAMP(3);
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "completed_at" TIMESTAMP(3);
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- event_reward_configs
CREATE TABLE IF NOT EXISTS "event_reward_configs" (
    "id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "gold_supply" INTEGER NOT NULL DEFAULT 1,
    "gold_points" INTEGER NOT NULL DEFAULT 100,
    "gold_image_url" TEXT,
    "gold_name" TEXT NOT NULL DEFAULT 'Gold Medal',
    "silver_supply" INTEGER NOT NULL DEFAULT 3,
    "silver_points" INTEGER NOT NULL DEFAULT 60,
    "silver_image_url" TEXT,
    "silver_name" TEXT NOT NULL DEFAULT 'Silver Medal',
    "bronze_supply" INTEGER NOT NULL DEFAULT 5,
    "bronze_points" INTEGER NOT NULL DEFAULT 30,
    "bronze_image_url" TEXT,
    "bronze_name" TEXT NOT NULL DEFAULT 'Bronze Medal',
    "minting_status" TEXT NOT NULL DEFAULT 'PENDING',
    "minting_error" TEXT,
    "minted_count" INTEGER NOT NULL DEFAULT 0,
    "total_to_mint" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "event_reward_configs_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "event_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "gold_supply" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "gold_points" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "gold_image_url" TEXT;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "gold_name" TEXT NOT NULL DEFAULT 'Gold Medal';
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "silver_supply" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "silver_points" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "silver_image_url" TEXT;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "silver_name" TEXT NOT NULL DEFAULT 'Silver Medal';
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "bronze_supply" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "bronze_points" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "bronze_image_url" TEXT;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "bronze_name" TEXT NOT NULL DEFAULT 'Bronze Medal';
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "minting_status" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "minting_error" TEXT;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "minted_count" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "total_to_mint" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "event_reward_configs" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- event_entries
CREATE TABLE IF NOT EXISTS "event_entries" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "wallet_address" TEXT NOT NULL,
    "amount" DECIMAL(65,30) NOT NULL,
    "tx_hash" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "event_entries_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "event_entries" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_entries" ADD COLUMN IF NOT EXISTS "user_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_entries" ADD COLUMN IF NOT EXISTS "event_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_entries" ADD COLUMN IF NOT EXISTS "wallet_address" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_entries" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(65,30) NOT NULL DEFAULT 0;
ALTER TABLE "event_entries" ADD COLUMN IF NOT EXISTS "tx_hash" TEXT;
ALTER TABLE "event_entries" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "event_entries" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "event_entries" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- event_escrows
CREATE TABLE IF NOT EXISTS "event_escrows" (
    "id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "event_entry_id" TEXT,
    "event_id_on_chain" TEXT NOT NULL,
    "participant_id" TEXT NOT NULL,
    "participant_wallet" TEXT NOT NULL,
    "event_creator_wallet" TEXT NOT NULL,
    "escrow_pda" TEXT NOT NULL,
    "amount" DECIMAL(65,30) NOT NULL,
    "status" TEXT NOT NULL,
    "deposit_tx_hash" TEXT,
    "release_tx_hash" TEXT,
    "confirmed_at" TIMESTAMP(3),
    "released_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "event_escrows_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "event_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "event_entry_id" TEXT;
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "event_id_on_chain" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "participant_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "participant_wallet" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "event_creator_wallet" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "escrow_pda" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(65,30) NOT NULL DEFAULT 0;
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "deposit_tx_hash" TEXT;
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "release_tx_hash" TEXT;
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "confirmed_at" TIMESTAMP(3);
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "released_at" TIMESTAMP(3);
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "event_escrows" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- reward_accounts
CREATE TABLE IF NOT EXISTS "reward_accounts" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "wallet_address" TEXT NOT NULL,
    "interaction_count" INTEGER NOT NULL DEFAULT 0,
    "claimed_nfts" INTEGER NOT NULL DEFAULT 0,
    "reward_pda" TEXT,
    "last_interaction_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "reward_accounts_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "reward_accounts" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "reward_accounts" ADD COLUMN IF NOT EXISTS "user_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "reward_accounts" ADD COLUMN IF NOT EXISTS "wallet_address" TEXT NOT NULL DEFAULT '';
ALTER TABLE "reward_accounts" ADD COLUMN IF NOT EXISTS "interaction_count" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "reward_accounts" ADD COLUMN IF NOT EXISTS "claimed_nfts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "reward_accounts" ADD COLUMN IF NOT EXISTS "reward_pda" TEXT;
ALTER TABLE "reward_accounts" ADD COLUMN IF NOT EXISTS "last_interaction_at" TIMESTAMP(3);
ALTER TABLE "reward_accounts" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "reward_accounts" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- interactions
CREATE TABLE IF NOT EXISTS "interactions" (
    "id" TEXT NOT NULL,
    "reward_account_id" TEXT NOT NULL,
    "interaction_type" TEXT NOT NULL,
    "points" INTEGER NOT NULL DEFAULT 1,
    "metadata" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "interactions_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "interactions" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "interactions" ADD COLUMN IF NOT EXISTS "reward_account_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "interactions" ADD COLUMN IF NOT EXISTS "interaction_type" TEXT NOT NULL DEFAULT '';
ALTER TABLE "interactions" ADD COLUMN IF NOT EXISTS "points" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "interactions" ADD COLUMN IF NOT EXISTS "metadata" TEXT;
ALTER TABLE "interactions" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- reward_drafts
CREATE TABLE IF NOT EXISTS "reward_drafts" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "metadata_uri" TEXT,
    "image_url" TEXT,
    "image_file" TEXT,
    "required_points" INTEGER NOT NULL DEFAULT 100,
    "reward_type" TEXT NOT NULL DEFAULT 'MUSIC_NFT',
    "total_supply" INTEGER NOT NULL DEFAULT 1,
    "is_listed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "reward_drafts_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "metadata_uri" TEXT;
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "image_url" TEXT;
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "image_file" TEXT;
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "required_points" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "reward_type" TEXT NOT NULL DEFAULT 'MUSIC_NFT';
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "total_supply" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "is_listed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "reward_drafts" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- reward_nfts
CREATE TABLE IF NOT EXISTS "reward_nfts" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "nft_asset" TEXT NOT NULL,
    "metadata_uri" TEXT NOT NULL,
    "image_url" TEXT,
    "required_points" INTEGER NOT NULL,
    "reward_type" TEXT NOT NULL DEFAULT 'MUSIC_NFT',
    "admin_wallet" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "total_supply" INTEGER NOT NULL DEFAULT 1,
    "claimed_count" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "reward_nfts_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "nft_asset" TEXT NOT NULL DEFAULT '';
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "metadata_uri" TEXT NOT NULL DEFAULT '';
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "image_url" TEXT;
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "required_points" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "reward_type" TEXT NOT NULL DEFAULT 'MUSIC_NFT';
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "admin_wallet" TEXT NOT NULL DEFAULT '';
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "total_supply" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "claimed_count" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "reward_nfts" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- claimed_rewards
CREATE TABLE IF NOT EXISTS "claimed_rewards" (
    "id" TEXT NOT NULL,
    "reward_account_id" TEXT NOT NULL,
    "reward_nft_id" TEXT,
    "nft_id" TEXT,
    "nft_asset" TEXT,
    "points_used" INTEGER NOT NULL,
    "reward_type" TEXT NOT NULL,
    "tx_hash" TEXT,
    "metadata" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "claimed_rewards_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "claimed_rewards" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "claimed_rewards" ADD COLUMN IF NOT EXISTS "reward_account_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "claimed_rewards" ADD COLUMN IF NOT EXISTS "reward_nft_id" TEXT;
ALTER TABLE "claimed_rewards" ADD COLUMN IF NOT EXISTS "nft_id" TEXT;
ALTER TABLE "claimed_rewards" ADD COLUMN IF NOT EXISTS "nft_asset" TEXT;
ALTER TABLE "claimed_rewards" ADD COLUMN IF NOT EXISTS "points_used" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "claimed_rewards" ADD COLUMN IF NOT EXISTS "reward_type" TEXT NOT NULL DEFAULT '';
ALTER TABLE "claimed_rewards" ADD COLUMN IF NOT EXISTS "tx_hash" TEXT;
ALTER TABLE "claimed_rewards" ADD COLUMN IF NOT EXISTS "metadata" TEXT;
ALTER TABLE "claimed_rewards" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- disputes
CREATE TABLE IF NOT EXISTS "disputes" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "event_id" TEXT,
    "event_entry_id" TEXT,
    "wallet_address" TEXT NOT NULL,
    "amount" DECIMAL(65,30) NOT NULL,
    "reason" TEXT NOT NULL,
    "transaction_id" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "admin_notes" TEXT,
    "refund_tx_hash" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolved_at" TIMESTAMP(3),

    CONSTRAINT "disputes_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "user_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "event_id" TEXT;
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "event_entry_id" TEXT;
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "wallet_address" TEXT NOT NULL DEFAULT '';
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(65,30) NOT NULL DEFAULT 0;
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "reason" TEXT NOT NULL DEFAULT '';
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "transaction_id" TEXT;
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "admin_notes" TEXT;
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "refund_tx_hash" TEXT;
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "disputes" ADD COLUMN IF NOT EXISTS "resolved_at" TIMESTAMP(3);

-- event_reward_nfts
CREATE TABLE IF NOT EXISTS "event_reward_nfts" (
    "id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "medal_type" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "image_url" TEXT NOT NULL,
    "metadata_uri" TEXT NOT NULL,
    "nft_asset" TEXT,
    "required_points" INTEGER NOT NULL,
    "total_supply" INTEGER NOT NULL DEFAULT 1,
    "claimed_count" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "event_reward_nfts_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "event_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "medal_type" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "image_url" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "metadata_uri" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "nft_asset" TEXT;
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "required_points" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "total_supply" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "claimed_count" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "event_reward_nfts" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- event_user_progress
CREATE TABLE IF NOT EXISTS "event_user_progress" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "wallet_address" TEXT NOT NULL,
    "total_points" INTEGER NOT NULL DEFAULT 0,
    "tasks_completed" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "event_user_progress_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "event_user_progress" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_user_progress" ADD COLUMN IF NOT EXISTS "user_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_user_progress" ADD COLUMN IF NOT EXISTS "event_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_user_progress" ADD COLUMN IF NOT EXISTS "wallet_address" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_user_progress" ADD COLUMN IF NOT EXISTS "total_points" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "event_user_progress" ADD COLUMN IF NOT EXISTS "tasks_completed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "event_user_progress" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "event_user_progress" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- event_reward_claims
CREATE TABLE IF NOT EXISTS "event_reward_claims" (
    "id" TEXT NOT NULL,
    "reward_nft_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "wallet_address" TEXT NOT NULL,
    "nft_asset" TEXT,
    "tx_hash" TEXT,
    "points_used" INTEGER NOT NULL,
    "claimed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "event_reward_claims_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "event_reward_claims" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_claims" ADD COLUMN IF NOT EXISTS "reward_nft_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_claims" ADD COLUMN IF NOT EXISTS "user_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_claims" ADD COLUMN IF NOT EXISTS "event_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_claims" ADD COLUMN IF NOT EXISTS "wallet_address" TEXT NOT NULL DEFAULT '';
ALTER TABLE "event_reward_claims" ADD COLUMN IF NOT EXISTS "nft_asset" TEXT;
ALTER TABLE "event_reward_claims" ADD COLUMN IF NOT EXISTS "tx_hash" TEXT;
ALTER TABLE "event_reward_claims" ADD COLUMN IF NOT EXISTS "points_used" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "event_reward_claims" ADD COLUMN IF NOT EXISTS "claimed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- albums
CREATE TABLE IF NOT EXISTS "albums" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "artist" TEXT NOT NULL,
    "description" TEXT,
    "cover_url" TEXT NOT NULL,
    "release_date" TIMESTAMP(3),
    "genre" TEXT,
    "total_tracks" INTEGER NOT NULL DEFAULT 0,
    "price" DECIMAL(65,30),
    "nft_asset" TEXT,
    "metadata_uri" TEXT,
    "creator_wallet" TEXT NOT NULL,
    "is_published" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "albums_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '';
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "artist" TEXT NOT NULL DEFAULT '';
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "cover_url" TEXT NOT NULL DEFAULT '';
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "release_date" TIMESTAMP(3);
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "genre" TEXT;
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "total_tracks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "price" DECIMAL(65,30);
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "nft_asset" TEXT;
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "metadata_uri" TEXT;
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "creator_wallet" TEXT NOT NULL DEFAULT '';
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "is_published" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "albums" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- tracks
CREATE TABLE IF NOT EXISTS "tracks" (
    "id" TEXT NOT NULL,
    "album_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "audio_url" TEXT NOT NULL,
    "artwork_url" TEXT,
    "duration" INTEGER,
    "track_number" INTEGER NOT NULL,
    "price" DECIMAL(65,30),
    "integrity_hash" TEXT,
    "nft_asset" TEXT,
    "metadata_uri" TEXT,
    "is_previewable" BOOLEAN NOT NULL DEFAULT true,
    "preview_duration" INTEGER NOT NULL DEFAULT 30,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tracks_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "album_id" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "audio_url" TEXT NOT NULL DEFAULT '';
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "artwork_url" TEXT;
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "duration" INTEGER;
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "track_number" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "price" DECIMAL(65,30);
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "integrity_hash" TEXT;
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "nft_asset" TEXT;
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "metadata_uri" TEXT;
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "is_previewable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "preview_duration" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "tracks" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS "wallets_wallet_address_key" ON "wallets"("wallet_address");
CREATE UNIQUE INDEX IF NOT EXISTS "nfts_nft_id_key" ON "nfts"("nft_id");
CREATE UNIQUE INDEX IF NOT EXISTS "transactions_transaction_id_key" ON "transactions"("transaction_id");
CREATE INDEX IF NOT EXISTS "transactions_wallet_address_idx" ON "transactions"("wallet_address");
CREATE INDEX IF NOT EXISTS "transactions_status_idx" ON "transactions"("status");
CREATE INDEX IF NOT EXISTS "transactions_transaction_type_idx" ON "transactions"("transaction_type");
CREATE INDEX IF NOT EXISTS "payment_logs_charge_id_idx" ON "payment_logs"("charge_id");
CREATE INDEX IF NOT EXISTS "payment_logs_wallet_address_idx" ON "payment_logs"("wallet_address");
CREATE INDEX IF NOT EXISTS "payment_logs_event_type_idx" ON "payment_logs"("event_type");
CREATE INDEX IF NOT EXISTS "events_creator_id_idx" ON "events"("creator_id");
CREATE INDEX IF NOT EXISTS "events_status_idx" ON "events"("status");
CREATE UNIQUE INDEX IF NOT EXISTS "event_reward_configs_event_id_key" ON "event_reward_configs"("event_id");
CREATE INDEX IF NOT EXISTS "event_entries_user_id_idx" ON "event_entries"("user_id");
CREATE INDEX IF NOT EXISTS "event_entries_event_id_idx" ON "event_entries"("event_id");
CREATE INDEX IF NOT EXISTS "event_entries_wallet_address_idx" ON "event_entries"("wallet_address");
CREATE UNIQUE INDEX IF NOT EXISTS "event_escrows_event_entry_id_key" ON "event_escrows"("event_entry_id");
CREATE INDEX IF NOT EXISTS "event_escrows_event_id_idx" ON "event_escrows"("event_id");
CREATE INDEX IF NOT EXISTS "event_escrows_participant_wallet_idx" ON "event_escrows"("participant_wallet");
CREATE INDEX IF NOT EXISTS "event_escrows_status_idx" ON "event_escrows"("status");
CREATE INDEX IF NOT EXISTS "event_escrows_escrow_pda_idx" ON "event_escrows"("escrow_pda");
CREATE UNIQUE INDEX IF NOT EXISTS "reward_accounts_user_id_key" ON "reward_accounts"("user_id");
CREATE INDEX IF NOT EXISTS "reward_accounts_wallet_address_idx" ON "reward_accounts"("wallet_address");
CREATE INDEX IF NOT EXISTS "reward_accounts_user_id_idx" ON "reward_accounts"("user_id");
CREATE INDEX IF NOT EXISTS "interactions_reward_account_id_idx" ON "interactions"("reward_account_id");
CREATE INDEX IF NOT EXISTS "interactions_created_at_idx" ON "interactions"("created_at");
CREATE INDEX IF NOT EXISTS "reward_drafts_is_listed_idx" ON "reward_drafts"("is_listed");
CREATE UNIQUE INDEX IF NOT EXISTS "reward_nfts_nft_asset_key" ON "reward_nfts"("nft_asset");
CREATE INDEX IF NOT EXISTS "reward_nfts_is_active_idx" ON "reward_nfts"("is_active");
CREATE INDEX IF NOT EXISTS "reward_nfts_required_points_idx" ON "reward_nfts"("required_points");
CREATE INDEX IF NOT EXISTS "claimed_rewards_reward_account_id_idx" ON "claimed_rewards"("reward_account_id");
CREATE INDEX IF NOT EXISTS "claimed_rewards_nft_asset_idx" ON "claimed_rewards"("nft_asset");
CREATE INDEX IF NOT EXISTS "claimed_rewards_reward_nft_id_idx" ON "claimed_rewards"("reward_nft_id");
CREATE INDEX IF NOT EXISTS "disputes_user_id_idx" ON "disputes"("user_id");
CREATE INDEX IF NOT EXISTS "disputes_status_idx" ON "disputes"("status");
CREATE INDEX IF NOT EXISTS "disputes_wallet_address_idx" ON "disputes"("wallet_address");
CREATE INDEX IF NOT EXISTS "disputes_event_id_idx" ON "disputes"("event_id");
CREATE UNIQUE INDEX IF NOT EXISTS "event_reward_nfts_nft_asset_key" ON "event_reward_nfts"("nft_asset");
CREATE INDEX IF NOT EXISTS "event_reward_nfts_event_id_idx" ON "event_reward_nfts"("event_id");
CREATE INDEX IF NOT EXISTS "event_reward_nfts_medal_type_idx" ON "event_reward_nfts"("medal_type");
CREATE INDEX IF NOT EXISTS "event_user_progress_event_id_idx" ON "event_user_progress"("event_id");
CREATE INDEX IF NOT EXISTS "event_user_progress_wallet_address_idx" ON "event_user_progress"("wallet_address");
CREATE UNIQUE INDEX IF NOT EXISTS "event_user_progress_user_id_event_id_key" ON "event_user_progress"("user_id", "event_id");
CREATE INDEX IF NOT EXISTS "event_reward_claims_user_id_idx" ON "event_reward_claims"("user_id");
CREATE INDEX IF NOT EXISTS "event_reward_claims_event_id_idx" ON "event_reward_claims"("event_id");
CREATE INDEX IF NOT EXISTS "event_reward_claims_reward_nft_id_idx" ON "event_reward_claims"("reward_nft_id");
CREATE UNIQUE INDEX IF NOT EXISTS "albums_nft_asset_key" ON "albums"("nft_asset");
CREATE INDEX IF NOT EXISTS "albums_artist_idx" ON "albums"("artist");
CREATE INDEX IF NOT EXISTS "albums_creator_wallet_idx" ON "albums"("creator_wallet");
CREATE INDEX IF NOT EXISTS "albums_is_published_idx" ON "albums"("is_published");
CREATE UNIQUE INDEX IF NOT EXISTS "tracks_nft_asset_key" ON "tracks"("nft_asset");
CREATE INDEX IF NOT EXISTS "tracks_album_id_idx" ON "tracks"("album_id");
CREATE INDEX IF NOT EXISTS "tracks_nft_asset_idx" ON "tracks"("nft_asset");

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'wallets_user_id_fkey') THEN
    ALTER TABLE "wallets" ADD CONSTRAINT "wallets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'nfts_wallet_id_fkey') THEN
    ALTER TABLE "nfts" ADD CONSTRAINT "nfts_wallet_id_fkey" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'escrows_nft_id_fkey') THEN
    ALTER TABLE "escrows" ADD CONSTRAINT "escrows_nft_id_fkey" FOREIGN KEY ("nft_id") REFERENCES "nfts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'escrows_user_id_fkey') THEN
    ALTER TABLE "escrows" ADD CONSTRAINT "escrows_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'transactions_nft_id_fkey') THEN
    ALTER TABLE "transactions" ADD CONSTRAINT "transactions_nft_id_fkey" FOREIGN KEY ("nft_id") REFERENCES "nfts"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'transactions_user_id_fkey') THEN
    ALTER TABLE "transactions" ADD CONSTRAINT "transactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'events_creator_id_fkey') THEN
    ALTER TABLE "events" ADD CONSTRAINT "events_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_reward_configs_event_id_fkey') THEN
    ALTER TABLE "event_reward_configs" ADD CONSTRAINT "event_reward_configs_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_entries_user_id_fkey') THEN
    ALTER TABLE "event_entries" ADD CONSTRAINT "event_entries_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_entries_event_id_fkey') THEN
    ALTER TABLE "event_entries" ADD CONSTRAINT "event_entries_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_escrows_event_id_fkey') THEN
    ALTER TABLE "event_escrows" ADD CONSTRAINT "event_escrows_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_escrows_event_entry_id_fkey') THEN
    ALTER TABLE "event_escrows" ADD CONSTRAINT "event_escrows_event_entry_id_fkey" FOREIGN KEY ("event_entry_id") REFERENCES "event_entries"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_accounts_user_id_fkey') THEN
    ALTER TABLE "reward_accounts" ADD CONSTRAINT "reward_accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'interactions_reward_account_id_fkey') THEN
    ALTER TABLE "interactions" ADD CONSTRAINT "interactions_reward_account_id_fkey" FOREIGN KEY ("reward_account_id") REFERENCES "reward_accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claimed_rewards_reward_account_id_fkey') THEN
    ALTER TABLE "claimed_rewards" ADD CONSTRAINT "claimed_rewards_reward_account_id_fkey" FOREIGN KEY ("reward_account_id") REFERENCES "reward_accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'claimed_rewards_reward_nft_id_fkey') THEN
    ALTER TABLE "claimed_rewards" ADD CONSTRAINT "claimed_rewards_reward_nft_id_fkey" FOREIGN KEY ("reward_nft_id") REFERENCES "reward_nfts"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'disputes_user_id_fkey') THEN
    ALTER TABLE "disputes" ADD CONSTRAINT "disputes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'disputes_event_id_fkey') THEN
    ALTER TABLE "disputes" ADD CONSTRAINT "disputes_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_reward_nfts_event_id_fkey') THEN
    ALTER TABLE "event_reward_nfts" ADD CONSTRAINT "event_reward_nfts_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_user_progress_user_id_fkey') THEN
    ALTER TABLE "event_user_progress" ADD CONSTRAINT "event_user_progress_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_user_progress_event_id_fkey') THEN
    ALTER TABLE "event_user_progress" ADD CONSTRAINT "event_user_progress_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_reward_claims_reward_nft_id_fkey') THEN
    ALTER TABLE "event_reward_claims" ADD CONSTRAINT "event_reward_claims_reward_nft_id_fkey" FOREIGN KEY ("reward_nft_id") REFERENCES "event_reward_nfts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_reward_claims_user_id_fkey') THEN
    ALTER TABLE "event_reward_claims" ADD CONSTRAINT "event_reward_claims_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'event_reward_claims_event_id_fkey') THEN
    ALTER TABLE "event_reward_claims" ADD CONSTRAINT "event_reward_claims_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tracks_album_id_fkey') THEN
    ALTER TABLE "tracks" ADD CONSTRAINT "tracks_album_id_fkey" FOREIGN KEY ("album_id") REFERENCES "albums"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

COMMIT;
