// Environment bindings this worker reads.
//
// Deliberately NOT in worker-configuration.d.ts. That file is regenerated by
// `npm run cf-typegen`, which rebuilds Cloudflare.Env from the bindings declared in
// wrangler.jsonc - and almost everything below is a secret, so none of it is declared there.
// Running cf-typegen with these in the generated file silently deletes every one and breaks
// the typecheck. Verified: a single cf-typegen run removed ADMIN_API_KEY, DATABASE_URL and
// SOLANA_RPC_URL along with the rest, and the deploy runbook tells you to run that command.
//
// TypeScript merges interfaces of the same name across ambient files, so this augments
// whatever the generator produces rather than competing with it. Regenerate freely.
//
// Note there is no `export {}` here on purpose: that would make this a module, and a
// `declare namespace` inside a module is local to it and merges with nothing.

declare namespace Cloudflare {
    interface Env {
        SOLANA_RPC_URL: string;
        DATABASE_URL: string;
        PUBLIC_URL?: string; // Public base URL for metadata/image URLs (e.g., https://your-worker.workers.dev or https://your-domain.com)
        BASE_SEPOLIA_RPC_URL?: string; // Base Sepolia RPC; defaults to publicnode (sepolia.base.org serves stale reads after writes)
        EVM_NFT_ADDRESS?: string;      // KumuleNFT proxy on Base Sepolia
        EVM_MARKET_ADDRESS?: string;   // KumuleMarket proxy on Base Sepolia
        MINT_FEE_LAMPORTS?: string;    // Optional Solana mint fee in lamports; unset means minting is free
        MINT_FEE_TREASURY?: string;    // Solana address that must receive the mint fee
        MEDAL_VAULT_PRIVATE_KEY?: string; // Base58 secret key of the wallet holding unclaimed medals
        ADMIN_API_KEY: string; // Admin API key for /api/admin/*; admin routes 503 until it is set
        ADMIN_WALLET_PRIVATE_KEY: string; // Admin wallet private key (base58) for auto-minting reward NFTs
        HYPERDRIVE: Hyperdrive;

        // --- stripe rail ---
        STRIPE_SECRET_KEY?: string;        // Restricted key (rk_...) scoped to PaymentIntents:write + Refunds:write
        STRIPE_WEBHOOK_SECRET?: string;    // whsec_...; the webhook 503s until it is set
        STRIPE_API_VERSION?: string;       // optional pin; unset means the account default
        MINT_ASSET_SEED?: string;          // HMAC root for deterministic asset addresses
        MINT_VAULT_PRIVATE_KEY?: string;   // base58 secret of the wallet that pays for mints
        MINT_SERVICE_PRICE_MINOR?: string; // Kumele's mint price in EUR cents; default 200
        TAX_RATE_BPS?: string;             // VAT in basis points; default 0
        MINT_FEE_FLOOR_MINOR?: string;     // floor on the blockchain fee line; default 15
        STRIPE_MIN_CHARGE_MINOR?: string;  // Stripe's per-currency minimum; default 50
        FEE_QUOTE_TTL_SECONDS?: string;    // quote lifetime; default 900
        ENABLE_DIRECT_CRYPTO?: string;     // "true" reopens the escrow and wallet-mint routes
    }
}
